{
  "name": "SemanticModel",
  "compatibilityLevel": 1500,
  "model": {
    "culture": "en-US",
    "dataSources": [
      {
        "type": "structured",
        "name": "SQL/localhost;NW_Traders_DW_old",
        "connectionDetails": {
          "protocol": "tds",
          "address": {
            "server": "localhost",
            "database": "NW_Traders_DW_old"
          },
          "authentication": null,
          "query": null
        },
        "options": {},
        "credential": {
          "AuthenticationKind": "Windows",
          "kind": "SQL",
          "path": "localhost;NW_Traders_DW_old",
          "Username": "bitdw\\bitstudent",
          "EncryptConnection": false
        }
      }
    ],
    "tables": [
      {
        "name": "DimCustomer",
        "columns": [
          {
            "name": "CustomerKey",
            "dataType": "int64",
            "sourceColumn": "CustomerKey"
          },
          {
            "name": "CustomerID",
            "dataType": "string",
            "sourceColumn": "CustomerID"
          },
          {
            "name": "CompanyName",
            "dataType": "string",
            "sourceColumn": "CompanyName"
          },
          {
            "name": "ContactName",
            "dataType": "string",
            "sourceColumn": "ContactName"
          },
          {
            "name": "ContactTitle",
            "dataType": "string",
            "sourceColumn": "ContactTitle"
          },
          {
            "name": "Address",
            "dataType": "string",
            "sourceColumn": "Address"
          },
          {
            "name": "City",
            "dataType": "string",
            "sourceColumn": "City"
          },
          {
            "name": "StateOrRegion",
            "dataType": "string",
            "sourceColumn": "StateOrRegion"
          },
          {
            "name": "CityState",
            "dataType": "string",
            "sourceColumn": "CityState"
          },
          {
            "name": "PostalCode",
            "dataType": "string",
            "sourceColumn": "PostalCode"
          },
          {
            "name": "Country",
            "dataType": "string",
            "sourceColumn": "Country"
          },
          {
            "name": "StartWhen",
            "dataType": "dateTime",
            "sourceColumn": "StartWhen"
          },
          {
            "name": "EndWhen",
            "dataType": "dateTime",
            "sourceColumn": "EndWhen"
          },
          {
            "name": "CurrentRecord",
            "dataType": "string",
            "sourceColumn": "CurrentRecord"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/localhost;NW_Traders_DW_old\",",
                "    dbo_DimCustomer = Source{[Schema=\"dbo\",Item=\"DimCustomer\"]}[Data]",
                "in",
                "    dbo_DimCustomer"
              ]
            }
          }
        ]
      },
      {
        "name": "Date",
        "dataCategory": "Time",
        "columns": [
          {
            "name": "DateKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "DateKey"
          },
          {
            "name": "Date",
            "dataType": "dateTime",
            "isKey": true,
            "sourceColumn": "Date"
          },
          {
            "name": "Day Of Week",
            "dataType": "int64",
            "sourceColumn": "DayOfWeek"
          },
          {
            "name": "Day Name",
            "dataType": "string",
            "sourceColumn": "DayName"
          },
          {
            "name": "Day Of Month",
            "dataType": "int64",
            "sourceColumn": "DayOfMonth"
          },
          {
            "name": "Month Name",
            "dataType": "string",
            "sourceColumn": "MonthName"
          },
          {
            "name": "Month",
            "dataType": "int64",
            "sourceColumn": "Month"
          },
          {
            "name": "Year",
            "dataType": "int64",
            "sourceColumn": "Year"
          },
          {
            "name": "Day Of Year",
            "dataType": "int64",
            "sourceColumn": "DayOfYear"
          },
          {
            "name": "Year Month",
            "dataType": "int64",
            "sourceColumn": "YearMonth"
          },
          {
            "name": "Quarter",
            "dataType": "int64",
            "sourceColumn": "Quarter"
          },
          {
            "name": "Quarter Name",
            "dataType": "string",
            "sourceColumn": "QuarterName"
          },
          {
            "name": "Year Quarter",
            "dataType": "string",
            "sourceColumn": "YearQuarter"
          },
          {
            "name": "Week Of Year",
            "dataType": "int64",
            "sourceColumn": "WeekOfYear"
          },
          {
            "type": "calculated",
            "name": "Month Description",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": "[Month]&\" - \"&[Month Name]"
          },
          {
            "type": "calculated",
            "name": "Week Description",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": "[Day Of Week]& \" - \" & [Day Name]"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/localhost;NW_Traders_DW_old\",",
                "    dbo_DimDate = Source{[Schema=\"dbo\",Item=\"DimDate\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_DimDate, each [Date] <= DateTime.LocalNow()),",
                "    #\"Sorted Rows\" = Table.Sort(#\"Filtered Rows\",{{\"Date\", Order.Descending}})",
                "in",
                "    #\"Sorted Rows\""
              ]
            }
          }
        ],
        "hierarchies": [
          {
            "name": "Calendar",
            "levels": [
              {
                "name": "Year",
                "ordinal": 0,
                "column": "Year"
              },
              {
                "name": "Quarter",
                "ordinal": 1,
                "column": "Quarter"
              },
              {
                "name": "Month Description",
                "ordinal": 2,
                "column": "Month Description"
              },
              {
                "name": "Week Description",
                "ordinal": 3,
                "column": "Week Description"
              },
              {
                "name": "Day Of Month",
                "ordinal": 4,
                "column": "Day Of Month"
              }
            ]
          }
        ]
      },
      {
        "name": "DimEmployee",
        "columns": [
          {
            "name": "EmployeeKey",
            "dataType": "int64",
            "sourceColumn": "EmployeeKey"
          },
          {
            "name": "EmployeeID",
            "dataType": "int64",
            "sourceColumn": "EmployeeID"
          },
          {
            "name": "FirstName",
            "dataType": "string",
            "sourceColumn": "FirstName"
          },
          {
            "name": "LastName",
            "dataType": "string",
            "sourceColumn": "LastName"
          },
          {
            "name": "FullName",
            "dataType": "string",
            "sourceColumn": "FullName"
          },
          {
            "name": "JobTitle",
            "dataType": "string",
            "sourceColumn": "JobTitle"
          },
          {
            "name": "EmployeeStatus",
            "dataType": "string",
            "sourceColumn": "EmployeeStatus"
          },
          {
            "name": "StartWhen",
            "dataType": "dateTime",
            "sourceColumn": "StartWhen"
          },
          {
            "name": "EndWhen",
            "dataType": "dateTime",
            "sourceColumn": "EndWhen"
          },
          {
            "name": "CurrentRecord",
            "dataType": "string",
            "sourceColumn": "CurrentRecord"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/localhost;NW_Traders_DW_old\",",
                "    dbo_DimEmployee = Source{[Schema=\"dbo\",Item=\"DimEmployee\"]}[Data]",
                "in",
                "    dbo_DimEmployee"
              ]
            }
          }
        ]
      },
      {
        "name": "Products",
        "columns": [
          {
            "name": "ProductKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "ProductKey"
          },
          {
            "name": "ProductID",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "ProductID"
          },
          {
            "name": "Product Name",
            "dataType": "string",
            "sourceColumn": "ProductName"
          },
          {
            "name": "Product Category",
            "dataType": "string",
            "sourceColumn": "CategoryName"
          },
          {
            "name": "Supplier",
            "dataType": "string",
            "sourceColumn": "SupplierName"
          },
          {
            "name": "Quantity per Unit",
            "dataType": "string",
            "sourceColumn": "QtyPerUnit"
          },
          {
            "name": "Wholesale Price",
            "dataType": "double",
            "sourceColumn": "WholesalePrice"
          },
          {
            "name": "Product Status",
            "dataType": "string",
            "sourceColumn": "ProductStatus"
          },
          {
            "name": "StartWhen",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "StartWhen"
          },
          {
            "name": "EndWhen",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "EndWhen"
          },
          {
            "name": "CurrentRecord",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "CurrentRecord"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/localhost;NW_Traders_DW_old\",",
                "    dbo_DimProduct = Source{[Schema=\"dbo\",Item=\"DimProduct\"]}[Data]",
                "in",
                "    dbo_DimProduct"
              ]
            }
          }
        ],
        "hierarchies": [
          {
            "name": "Product Hierarchy",
            "levels": [
              {
                "name": "Product Category",
                "ordinal": 0,
                "column": "Product Category"
              },
              {
                "name": "Product Name",
                "ordinal": 1,
                "column": "Product Name"
              }
            ]
          }
        ]
      },
      {
        "name": "DimShipper",
        "columns": [
          {
            "name": "ShipperKey",
            "dataType": "int64",
            "sourceColumn": "ShipperKey"
          },
          {
            "name": "ShipperID",
            "dataType": "int64",
            "sourceColumn": "ShipperID"
          },
          {
            "name": "ShipperName",
            "dataType": "string",
            "sourceColumn": "ShipperName"
          },
          {
            "name": "PrevShipperName",
            "dataType": "string",
            "sourceColumn": "PrevShipperName"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/localhost;NW_Traders_DW_old\",",
                "    dbo_DimShipper = Source{[Schema=\"dbo\",Item=\"DimShipper\"]}[Data]",
                "in",
                "    dbo_DimShipper"
              ]
            }
          }
        ]
      },
      {
        "name": "DimSupplier",
        "columns": [
          {
            "name": "SupplierKey",
            "dataType": "int64",
            "sourceColumn": "SupplierKey"
          },
          {
            "name": "SupplierID",
            "dataType": "int64",
            "sourceColumn": "SupplierID"
          },
          {
            "name": "SupplierName",
            "dataType": "string",
            "sourceColumn": "SupplierName"
          },
          {
            "name": "SupplierContactName",
            "dataType": "string",
            "sourceColumn": "SupplierContactName"
          },
          {
            "name": "PrevSupplierName",
            "dataType": "string",
            "sourceColumn": "PrevSupplierName"
          },
          {
            "name": "PrevSupplierContactName",
            "dataType": "string",
            "sourceColumn": "PrevSupplierContactName"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/localhost;NW_Traders_DW_old\",",
                "    dbo_DimSupplier = Source{[Schema=\"dbo\",Item=\"DimSupplier\"]}[Data]",
                "in",
                "    dbo_DimSupplier"
              ]
            }
          }
        ]
      },
      {
        "name": "Orders",
        "columns": [
          {
            "name": "OrderLineKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "OrderLineKey"
          },
          {
            "name": "LineID",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "LineID"
          },
          {
            "name": "ProductKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "ProductKey"
          },
          {
            "name": "OrderDateKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "OrderDateKey"
          },
          {
            "name": "Order Date Time",
            "dataType": "dateTime",
            "sourceColumn": "OrderDateTime"
          },
          {
            "name": "RequiredDateKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "RequiredDateKey"
          },
          {
            "name": "Required Date Time",
            "dataType": "dateTime",
            "sourceColumn": "RequiredDateTime"
          },
          {
            "name": "ShippedDateKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "ShippedDateKey"
          },
          {
            "name": "Shipped Date Time",
            "dataType": "dateTime",
            "sourceColumn": "ShippedDateTime"
          },
          {
            "name": "EmployeeKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "EmployeeKey"
          },
          {
            "name": "ShipperKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "ShipperKey"
          },
          {
            "name": "CustomerKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "CustomerKey"
          },
          {
            "name": "SupplierKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "SupplierKey"
          },
          {
            "name": "Quantity",
            "dataType": "int64",
            "sourceColumn": "Quantity"
          },
          {
            "name": "Unit List Price",
            "dataType": "double",
            "sourceColumn": "UnitListPrice"
          },
          {
            "name": "Unit Discount Amount",
            "dataType": "double",
            "sourceColumn": "UnitDiscount"
          },
          {
            "name": "Unit Net Price",
            "dataType": "double",
            "sourceColumn": "UnitNetPrice"
          },
          {
            "name": "Extended List Price",
            "dataType": "double",
            "sourceColumn": "ExtendedListPrice"
          },
          {
            "name": "Extended Discount",
            "dataType": "double",
            "sourceColumn": "ExtendedDiscount"
          },
          {
            "name": "Extended Net Price",
            "dataType": "double",
            "sourceColumn": "ExtendedNetPrice"
          },
          {
            "name": "Cost Allocated Freight",
            "dataType": "double",
            "sourceColumn": "CostAllocatedFreight"
          },
          {
            "type": "calculated",
            "name": "Line Total",
            "dataType": "double",
            "isDataTypeInferred": true,
            "expression": "[Extended Net Price]*[Quantity]"
          },
          {
            "type": "calculated",
            "name": "Unit Discount %",
            "dataType": "double",
            "isDataTypeInferred": true,
            "expression": "[Unit Discount Amount]/[Unit List Price]"
          },
          {
            "type": "calculated",
            "name": "Days To Ship",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "expression": "DATEDIFF([Order Date Time],[Shipped Date Time],DAY)"
          },
          {
            "type": "calculated",
            "name": "Days Overdue",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "expression": "IF(DATEDIFF([Required Date Time],[Shipped Date Time],DAY)>0,DATEDIFF([Required Date Time],[Shipped Date Time],DAY),BLANK())"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/localhost;NW_Traders_DW_old\",",
                "    dbo_FactOrder = Source{[Schema=\"dbo\",Item=\"FactOrder\"]}[Data],",
                "    #\"Changed Type\" = Table.TransformColumnTypes(dbo_FactOrder,{{\"UnitNetPrice\", type number}})",
                "in",
                "    #\"Changed Type\""
              ]
            }
          }
        ]
      },
      {
        "name": "Sales Measures",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "col1",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[col1]"
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": " DataTable(\"col1\", STRING,{{\"\"}})"
            }
          }
        ],
        "measures": [
          {
            "name": "Total Sales",
            "expression": "SUM(Orders[Line Total])"
          },
          {
            "name": "Total Discounts",
            "expression": "SUM(Orders[Extended Discount])"
          },
          {
            "name": "Total Units Sold",
            "expression": "SUM(Orders[Quantity])"
          },
          {
            "name": "Average Days To Ship",
            "expression": "AVERAGE(Orders[Days To Ship])"
          },
          {
            "name": "Average Days Overdue",
            "expression": "AVERAGE(Orders[Days Overdue])"
          },
          {
            "name": "Year To Date Sales",
            "expression": "TOTALYTD([Total Sales],'Date'[Date])"
          },
          {
            "name": "Sales Last Year",
            "expression": "CALCULATE([Total Sales],PARALLELPERIOD('Date'[Date],-1,YEAR))"
          },
          {
            "name": "Year Over Years Sales",
            "expression": "[Year To Date Sales]-'Sales Measures'[Sales Last Year]"
          },
          {
            "name": "Amount Shipped $",
            "expression": "CALCULATE([Total Sales],USERELATIONSHIP(Orders[ShippedDateKey],'Date'[DateKey]))"
          },
          {
            "name": "Average Sales",
            "expression": " AVERAGE(Orders[Line Total])"
          },
          {
            "name": "Total Orders",
            "expression": "COUNT(Orders[LineID])"
          },
          {
            "name": "Total Shipped Orders",
            "expression": "COUNT(Orders[Shipped Date Time])"
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "710ab6fd-ca6a-40f7-903f-d84589f4a7ff",
        "fromTable": "Orders",
        "fromColumn": "RequiredDateKey",
        "toTable": "Date",
        "toColumn": "DateKey",
        "isActive": false
      },
      {
        "name": "4f52045e-408a-40e8-99cb-8ae617dcbb0b",
        "fromTable": "Orders",
        "fromColumn": "ShippedDateKey",
        "toTable": "Date",
        "toColumn": "DateKey",
        "isActive": false
      },
      {
        "name": "b4f7f67f-56d9-44da-94ea-b847e7285136",
        "fromTable": "Orders",
        "fromColumn": "CustomerKey",
        "toTable": "DimCustomer",
        "toColumn": "CustomerKey"
      },
      {
        "name": "83900477-85d4-4069-99d5-d0ec6193da6a",
        "fromTable": "Orders",
        "fromColumn": "OrderDateKey",
        "toTable": "Date",
        "toColumn": "DateKey"
      },
      {
        "name": "9e2f9431-3959-4601-8fcd-a68812f28bcc",
        "fromTable": "Orders",
        "fromColumn": "EmployeeKey",
        "toTable": "DimEmployee",
        "toColumn": "EmployeeKey"
      },
      {
        "name": "489168be-420c-4083-adcd-6ee38e8ce127",
        "fromTable": "Orders",
        "fromColumn": "ProductKey",
        "toTable": "Products",
        "toColumn": "ProductKey"
      },
      {
        "name": "6db5b949-ac8c-46dc-835d-8632993b3730",
        "fromTable": "Orders",
        "fromColumn": "ShipperKey",
        "toTable": "DimShipper",
        "toColumn": "ShipperKey"
      },
      {
        "name": "56552a0c-0eb5-4b9a-80ff-de913be18f07",
        "fromTable": "Orders",
        "fromColumn": "SupplierKey",
        "toTable": "DimSupplier",
        "toColumn": "SupplierKey"
      }
    ],
    "roles": [
      {
        "name": "Process Database",
        "modelPermission": "refresh"
      },
      {
        "name": "Sales Reporting User",
        "modelPermission": "read"
      },
      {
        "name": "Sales Reporting Administrators",
        "modelPermission": "administrator"
      }
    ],
    "annotations": [
      {
        "name": "ClientCompatibilityLevel",
        "value": "600"
      }
    ]
  },
  "id": "SemanticModel"
}