{
  "name": "SemanticModel",
  "compatibilityLevel": 1500,
  "model": {
    "culture": "en-US",
    "dataSources": [
      {
        "type": "structured",
        "name": "SQL/localhost;SakilaDW_AGA",
        "connectionDetails": {
          "protocol": "tds",
          "address": {
            "server": "localhost",
            "database": "SakilaDW_AGA"
          },
          "authentication": null,
          "query": null
        },
        "options": {},
        "credential": {
          "AuthenticationKind": "Windows",
          "kind": "SQL",
          "path": "localhost;SakilaDW_AGA",
          "Username": "bitdw\\bitstudent",
          "EncryptConnection": false
        }
      }
    ],
    "tables": [
      {
        "name": "Dates",
        "dataCategory": "Time",
        "columns": [
          {
            "name": "DateKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "DateKey"
          },
          {
            "name": "Date",
            "dataType": "dateTime",
            "isKey": true,
            "sourceColumn": "Date"
          },
          {
            "name": "Day Of The Month",
            "dataType": "int64",
            "sourceColumn": "DayOfMonth"
          },
          {
            "name": "Month Number",
            "dataType": "int64",
            "sourceColumn": "MonthNumber"
          },
          {
            "name": "Month Name",
            "dataType": "string",
            "sourceColumn": "MonthName"
          },
          {
            "name": "Year",
            "dataType": "int64",
            "sourceColumn": "Year"
          },
          {
            "name": "Day Of The Week Name",
            "dataType": "string",
            "sourceColumn": "DayOfWeekName"
          },
          {
            "name": "Day Of The Week Number",
            "dataType": "int64",
            "sourceColumn": "DayOfWeekNumber"
          },
          {
            "name": "Is Weekend",
            "dataType": "boolean",
            "sourceColumn": "IsWeekend"
          },
          {
            "type": "calculated",
            "name": "Date Text",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": "[Month Name]&\" \"&[Day Of The Month]&\", \"&[Year]"
          },
          {
            "type": "calculated",
            "name": "Date Text w/ Day",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": "[Day Of The Week Name]&\", \"&[Date Text]"
          },
          {
            "type": "calculated",
            "name": "Month Description",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": "[Month Number]&\" - \"&[Month Name]"
          },
          {
            "type": "calculated",
            "name": "Week Description",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": "[Day Of The Week Number]&\" - \"&[Day Of The Week Name]"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/localhost;SakilaDW_AGA\",",
                "    dbo_DimDate = Source{[Schema=\"dbo\",Item=\"DimDate\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_DimDate, each [Date] <= Date.From(DateTime.LocalNow()) and [Date] <> #date(1900, 1, 1)),",
                "    #\"Sorted Rows\" = Table.Sort(#\"Filtered Rows\",{{\"Date\", Order.Ascending}})",
                "in",
                "    #\"Sorted Rows\""
              ]
            }
          }
        ],
        "hierarchies": [
          {
            "name": "Calendar",
            "levels": [
              {
                "name": "Year",
                "ordinal": 0,
                "column": "Year"
              },
              {
                "name": "Month Description",
                "ordinal": 1,
                "column": "Month Description"
              },
              {
                "name": "Week Description",
                "ordinal": 2,
                "column": "Week Description"
              },
              {
                "name": "Day Of The Month",
                "ordinal": 3,
                "column": "Day Of The Month"
              }
            ]
          }
        ]
      },
      {
        "name": "Films",
        "columns": [
          {
            "name": "FilmKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "FilmKey"
          },
          {
            "name": "FilmID",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "FilmID"
          },
          {
            "name": "Film Titile",
            "dataType": "string",
            "sourceColumn": "Title"
          },
          {
            "name": "Film Description",
            "dataType": "string",
            "sourceColumn": "Description"
          },
          {
            "name": "Film Release Year",
            "dataType": "double",
            "sourceColumn": "ReleaseYear"
          },
          {
            "name": "Film Rental Duration",
            "dataType": "int64",
            "sourceColumn": "RentalDuration"
          },
          {
            "name": "Film Rental Rate",
            "dataType": "double",
            "sourceColumn": "RentalRate"
          },
          {
            "name": "Film Length",
            "dataType": "int64",
            "sourceColumn": "Length"
          },
          {
            "name": "Film Replacement Cost",
            "dataType": "double",
            "sourceColumn": "ReplacementCost"
          },
          {
            "name": "Film Rating",
            "dataType": "string",
            "sourceColumn": "Rating"
          },
          {
            "name": "Film Special Features",
            "dataType": "string",
            "sourceColumn": "SpecialFeatures"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/localhost;SakilaDW_AGA\",",
                "    dbo_DimFilm = Source{[Schema=\"dbo\",Item=\"DimFilm\"]}[Data]",
                "in",
                "    dbo_DimFilm"
              ]
            }
          }
        ]
      },
      {
        "name": "Film Categories",
        "columns": [
          {
            "name": "FilmCategoryKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "FilmCategoryKey"
          },
          {
            "name": "CategoryID",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "CategoryID"
          },
          {
            "name": "Film Category Name",
            "dataType": "string",
            "sourceColumn": "CategoryName"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/localhost;SakilaDW_AGA\",",
                "    dbo_DimFilmCategory = Source{[Schema=\"dbo\",Item=\"DimFilmCategory\"]}[Data]",
                "in",
                "    dbo_DimFilmCategory"
              ]
            }
          }
        ]
      },
      {
        "name": "Film Languages",
        "columns": [
          {
            "name": "FilmLanguageKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "FilmLanguageKey"
          },
          {
            "name": "LanguageID",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "LanguageID"
          },
          {
            "name": "Film Language Name",
            "dataType": "string",
            "sourceColumn": "LanguageName"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/localhost;SakilaDW_AGA\",",
                "    dbo_DimFilmLanguage = Source{[Schema=\"dbo\",Item=\"DimFilmLanguage\"]}[Data]",
                "in",
                "    dbo_DimFilmLanguage"
              ]
            }
          }
        ]
      },
      {
        "name": "Rental Cities",
        "columns": [
          {
            "name": "RentalCityKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "RentalCityKey"
          },
          {
            "name": "CityID",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "CityID"
          },
          {
            "name": "Rental City Name",
            "dataType": "string",
            "sourceColumn": "CityName"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/localhost;SakilaDW_AGA\",",
                "    dbo_DimRentalCity = Source{[Schema=\"dbo\",Item=\"DimRentalCity\"]}[Data]",
                "in",
                "    dbo_DimRentalCity"
              ]
            }
          }
        ]
      },
      {
        "name": "Rental Countries",
        "columns": [
          {
            "name": "RentalCountryKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "RentalCountryKey"
          },
          {
            "name": "CountryID",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "CountryID"
          },
          {
            "name": "Rental Country Name",
            "dataType": "string",
            "sourceColumn": "CountryName"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/localhost;SakilaDW_AGA\",",
                "    dbo_DimRentalCountry = Source{[Schema=\"dbo\",Item=\"DimRentalCountry\"]}[Data]",
                "in",
                "    dbo_DimRentalCountry"
              ]
            }
          }
        ]
      },
      {
        "name": "Stores",
        "columns": [
          {
            "name": "StoreKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "StoreKey"
          },
          {
            "name": "StoreID",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "StoreID"
          },
          {
            "name": "StoreManagerFirstName",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "StoreManagerFirstName"
          },
          {
            "name": "StoreManagerLastName",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "StoreManagerLastName"
          },
          {
            "name": "Store Manager Email",
            "dataType": "string",
            "sourceColumn": "StoreManagerEmail"
          },
          {
            "name": "Store Address Line 1",
            "dataType": "string",
            "sourceColumn": "StoreAddressLine1"
          },
          {
            "name": "Store Addres sLine 2",
            "dataType": "string",
            "sourceColumn": "StoreAddressLine2"
          },
          {
            "name": "Store District",
            "dataType": "string",
            "sourceColumn": "StoreDistrict"
          },
          {
            "name": "Store City",
            "dataType": "string",
            "sourceColumn": "StoreCity"
          },
          {
            "name": "Store Country",
            "dataType": "string",
            "sourceColumn": "StoreCountry"
          },
          {
            "name": "Store Postal Code",
            "dataType": "string",
            "sourceColumn": "StorePostalCode"
          },
          {
            "name": "Store Phone",
            "dataType": "string",
            "sourceColumn": "StorePhone"
          },
          {
            "type": "calculated",
            "name": "Store Manager Name",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": "([StoreManagerFirstName]&\" \"&[StoreManagerLastName])"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/localhost;SakilaDW_AGA\",",
                "    dbo_DimStore = Source{[Schema=\"dbo\",Item=\"DimStore\"]}[Data]",
                "in",
                "    dbo_DimStore"
              ]
            }
          }
        ]
      },
      {
        "name": "Rentals",
        "columns": [
          {
            "name": "RentalKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "RentalKey"
          },
          {
            "name": "RentalID",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "RentalID"
          },
          {
            "name": "Rental Date",
            "dataType": "dateTime",
            "sourceColumn": "RentalDate"
          },
          {
            "name": "Return Date",
            "dataType": "dateTime",
            "sourceColumn": "ReturnDate"
          },
          {
            "name": "RentalDuration",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "RentalDuration"
          },
          {
            "name": "Rental Amount",
            "dataType": "double",
            "sourceColumn": "Amount"
          },
          {
            "name": "Payment Date",
            "dataType": "dateTime",
            "sourceColumn": "PaymentDate"
          },
          {
            "name": "FilmKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "FilmKey"
          },
          {
            "name": "FilmCategoryKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "FilmCategoryKey"
          },
          {
            "name": "FilmLanguageKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "FilmLanguageKey"
          },
          {
            "name": "RentalCityKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "RentalCityKey"
          },
          {
            "name": "RentalCountryKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "RentalCountryKey"
          },
          {
            "name": "CustomerKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "CustomerKey"
          },
          {
            "name": "StoreKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "StoreKey"
          },
          {
            "name": "RentalDateKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "RentalDateKey"
          },
          {
            "name": "ReturnDateKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "ReturnDateKey"
          },
          {
            "name": "PaymentDateKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "PaymentDateKey"
          },
          {
            "type": "calculated",
            "name": "Rental Duration",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "expression": "IF(DATEDIFF([Rental Date],[Return Date],DAY)>0,DATEDIFF([Rental Date],[Return Date],DAY),BLANK())"
          },
          {
            "type": "calculated",
            "name": "Calculated Column 1",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "expression": "CALCULATE(COUNTX(Rentals, GROUPBY(Rentals,[CustomerKey])))"
          },
          {
            "type": "calculated",
            "name": "Calculated Column 2",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "expression": "DISTINCTCOUNT([CustomerKey])"
          },
          {
            "type": "calculated",
            "name": "Calculated Column 3",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "expression": "CALCULATE(DISTINCTCOUNT([CustomerKey]),ALLEXCEPT(Rentals,Rentals[Rental Date]))"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/localhost;SakilaDW_AGA\",",
                "    dbo_FactRental = Source{[Schema=\"dbo\",Item=\"FactRental\"]}[Data]",
                "in",
                "    dbo_FactRental"
              ]
            }
          }
        ]
      },
      {
        "name": "Rental Measures",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "col1",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[col1]"
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": " DATATABLE(\"col1\", STRING, {{\"\"}})"
            }
          }
        ],
        "measures": [
          {
            "name": "Total Rental Amount",
            "expression": "SUM(Rentals[Rental Amount])"
          },
          {
            "name": "Total Year to Date",
            "expression": "TOTALYTD([Total Rental Amount],Dates[Date])"
          },
          {
            "name": "Total Month to Date",
            "expression": "TOTALMTD([Total Rental Amount],Dates[Date])"
          },
          {
            "name": "Average Payment",
            "expression": "AVERAGE(Rentals[Rental Amount])"
          },
          {
            "name": "Total Rentals",
            "expression": "COUNT(Rentals[RentalKey])"
          },
          {
            "name": "Average Rental Duration",
            "expression": "AVERAGE(Rentals[Rental Duration])"
          },
          {
            "name": "Average Items on Rental",
            "expression": "[Count of Distinct Rentals]/[Count of Distinct Payment Dates]"
          },
          {
            "name": "Count of Distinct Payment Dates",
            "expression": "DISTINCTCOUNT(Rentals[Payment Date])"
          },
          {
            "name": "Count of Distinct Rentals",
            "expression": "DISTINCTCOUNT(Rentals[RentalID])"
          }
        ]
      },
      {
        "name": "Customers",
        "columns": [
          {
            "name": "CustomerKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "CustomerKey"
          },
          {
            "name": "CustomerID",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "CustomerID"
          },
          {
            "name": "CustomerFirstName",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "CustomerFirstName"
          },
          {
            "name": "CustomerLastName",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "CustomerLastName"
          },
          {
            "name": "Customer Email",
            "dataType": "string",
            "sourceColumn": "CustomerEmail"
          },
          {
            "name": "Customer Address Line 1",
            "dataType": "string",
            "sourceColumn": "CustomerAddressLine1"
          },
          {
            "name": "Customer Address Line 2",
            "dataType": "string",
            "sourceColumn": "CustomerAddressLine2"
          },
          {
            "name": "Customer District",
            "dataType": "string",
            "sourceColumn": "CustomerDistrict"
          },
          {
            "name": "Customer City",
            "dataType": "string",
            "sourceColumn": "CustomerCity"
          },
          {
            "name": "Customer Country",
            "dataType": "string",
            "sourceColumn": "CustomerCountry"
          },
          {
            "name": "Customer Postal Code",
            "dataType": "string",
            "sourceColumn": "CustomerPostalCode"
          },
          {
            "name": "Customer Phone",
            "dataType": "string",
            "sourceColumn": "CustomerPhone"
          },
          {
            "name": "Customer Is Active",
            "dataType": "boolean",
            "sourceColumn": "CustomerIsActive"
          },
          {
            "name": "CustomerCreateDate",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "CustomerCreateDate"
          },
          {
            "name": "StartDate",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "StartDate"
          },
          {
            "name": "EndDate",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "EndDate"
          },
          {
            "name": "CurrentRowIndicator",
            "dataType": "boolean",
            "isHidden": true,
            "sourceColumn": "CurrentRowIndicator"
          },
          {
            "type": "calculated",
            "name": "Customer Name",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": "[CustomerFirstName]&\" \"&[CustomerLastName]"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/localhost;SakilaDW_AGA\",",
                "    dbo_DimCustomer = Source{[Schema=\"dbo\",Item=\"DimCustomer\"]}[Data]",
                "in",
                "    dbo_DimCustomer"
              ]
            }
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "94698d47-5f6a-41f5-a2da-b925d23b9bd3",
        "fromTable": "Rentals",
        "fromColumn": "PaymentDateKey",
        "toTable": "Dates",
        "toColumn": "DateKey",
        "isActive": false
      },
      {
        "name": "9aed9c52-ed76-4691-b3ef-dab7344ece4c",
        "fromTable": "Rentals",
        "fromColumn": "ReturnDateKey",
        "toTable": "Dates",
        "toColumn": "DateKey",
        "isActive": false
      },
      {
        "name": "30c92296-4939-4734-bd09-58df71073493",
        "fromTable": "Rentals",
        "fromColumn": "RentalDateKey",
        "toTable": "Dates",
        "toColumn": "DateKey"
      },
      {
        "name": "f58a6dd7-d5b7-4e59-af10-aed78a47db6c",
        "fromTable": "Rentals",
        "fromColumn": "FilmKey",
        "toTable": "Films",
        "toColumn": "FilmKey"
      },
      {
        "name": "a82bdea0-825b-471c-a143-5f48780e377d",
        "fromTable": "Rentals",
        "fromColumn": "FilmCategoryKey",
        "toTable": "Film Categories",
        "toColumn": "FilmCategoryKey"
      },
      {
        "name": "1dd27773-6bd3-4fd9-863d-9f183fad3db5",
        "fromTable": "Rentals",
        "fromColumn": "FilmLanguageKey",
        "toTable": "Film Languages",
        "toColumn": "FilmLanguageKey"
      },
      {
        "name": "f76e3d14-65b2-4ba4-a679-df5363b82db1",
        "fromTable": "Rentals",
        "fromColumn": "RentalCityKey",
        "toTable": "Rental Cities",
        "toColumn": "RentalCityKey"
      },
      {
        "name": "a48e7d08-9a96-4f70-9cda-28e54c9ad797",
        "fromTable": "Rentals",
        "fromColumn": "RentalCountryKey",
        "toTable": "Rental Countries",
        "toColumn": "RentalCountryKey"
      },
      {
        "name": "5e47c0d9-e304-44a1-91ef-c2c85c1f61ef",
        "fromTable": "Rentals",
        "fromColumn": "StoreKey",
        "toTable": "Stores",
        "toColumn": "StoreKey"
      },
      {
        "name": "d7b5dfb3-9eca-4634-88e1-e329839612a7",
        "fromTable": "Rentals",
        "fromColumn": "CustomerKey",
        "toTable": "Customers",
        "toColumn": "CustomerKey"
      }
    ],
    "annotations": [
      {
        "name": "ClientCompatibilityLevel",
        "value": "600"
      }
    ]
  },
  "id": "SemanticModel"
}